# Adapted R-CMD-check workflow for rstan packages

on:
  push:
    branches: [dev, main, master]
  pull_request:
    branches: [dev, main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install system dependencies (Ubuntu only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libclang-dev \
            clang \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libgit2-dev \
            cmake \
            g++ \
            libgmp-dev

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: "all"
          extra-packages: |
            rcmdcheck
            rstan
            StanHeaders
            Rcpp
            RcppParallel
            inline

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true

